require: 
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'lib/generators/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'coverage/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 200

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 30

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
