:concurrency: 5
:queues:
  - critical
  - default
  - low

# use below to define a background cronjob for sidekiq worker
:schedule:
 generate_sales_statement_pdf:
   # run every 7th day of the month
   cron: '0 0 7 * *'
   class: GenerateSalesStatementPdfWorker 
