:concurrency: 5
:queues:
  - critical
  - default
  - low

# use below to define a background cronjob for sidekiq worker
:schedule:
#  example_task:
#    # run every minute
#    cron: "* * * * *"
#    class: ExampleWorker 
