name: Deploy to production

on:
  push:
    branches: [ production ]

env:
  APP_DIRECTORY: ~/jujucart-docker

jobs:
  test:
    uses: ./.github/workflows/ci_test.yml

  build:
    needs: [test]
    uses: ./.github/workflows/build.yml

  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [test, build] 
    environment: production

    steps:
      - name: Pulling docker images
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ vars.PRODUCTION_HOSTS }}
          privateKey: ${{ secrets.PRODUCTION_SSH_KEY }}
          command: |
            cd ${{ env.APP_DIRECTORY }}
            docker-compose pull api sidekiq
      - name: Run rails migration
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ vars.PRODUCTION_HOSTS }}
          privateKey: ${{ secrets.PRODUCTION_SSH_KEY }}
          command: |
            cd ${{ env.APP_DIRECTORY }}
            docker-compose run --rm api rails db:migrate
      - name: Recycle all the containers
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ vars.PRODUCTION_HOSTS }}
          privateKey: ${{ secrets.PRODUCTION_SSH_KEY }}
          command: |
            cd ${{ env.APP_DIRECTORY }}
            docker-compose down && docker-compose up -d
